### ISSUE TITLE
error: expected initializer before 'rotaryEncoder'

### ISSUE THREAD

**Issue by TA2WK** [felangga/slametradio#1]
When compile it I receive following error from Arduino IDE:
-------------------------------------------------------------------------------------------
SLAMETRADIO:166:16: error: expected initializer before 'rotaryEncoder'

 void IRAM_ATTR rotaryEncoder()

**Comment by felangga** [comment]
Which microcontroller do you use ?

**Comment by TA2WK** [comment]
Solved. My mistage by selecting wrong board. Currently running ESP32 Dev board. Was using STM32.
